akita-interest-mapping/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "publics/registrations",
    sessions: 'publics/sessions'
  }
  devise_for :admins, controllers: {
    sessions: "admins/sessions"
  }

  scope module: :publics do
    root to: 'homes#top'
    resources :users, only: [:index, :show, :edit, :update]
    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy]
    get 'users/:id/withdraw' => 'users#withdraw', as: 'user_withdraw'
  end

  namespace :admins do
    root to: 'homes#top'
    resources :users, only: [:index, :show, :edit, :update]
    resources :posts, only: [:index, :show, :edit, :update, :destroy]
  end
  
end

akita-interest-mapping/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :posts,dependent: :destroy

  has_one_attached :profile_image
  
  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path = Rails.root.join("app/assets/images/default_person.jpeg")
      profile_image.attach(io: File.open(file_path),filename: "default-image.jpg",content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

akita-interest-mapping/app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
end

akita-interest-mapping/app/controllers/publics/confirmations_controller.rb
# frozen_string_literal: true

class Publics::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

akita-interest-mapping/app/controllers/publics/homes_controller.rb
class Publics::HomesController < ApplicationController
  def top
    @posts = Post.all
    @towns = Town.all
    @categories = Category.all
  end
end

akita-interest-mapping/app/controllers/publics/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Publics::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

akita-interest-mapping/app/controllers/publics/passwords_controller.rb
# frozen_string_literal: true

class Publics::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

akita-interest-mapping/app/controllers/publics/posts_controller.rb
class Publics::PostsController < ApplicationController
  def new
    @user = current_user
    @towns = Town.all
    @categories = Category.all
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if Town.find_by(name: @post.town_name)
      town = Town.find_by(name: @post.town_name)
      @post.town_id = town.id
      
    else
      @post.town_id = nil
    end
    @post.user_id = current_user.id
    if @post.save
      redirect_to user_path(current_user.id)
    else
      @user = current_user
      @towns = Town.all
      @categories = Category.all
      render :new
    end
  end

  def index
    @posts = Post.all
    @towns = Town.all
    @categories = Category.all
  end

  def show
  end

  def edit
    @post = Post.find(params[:id])
    @town = Town.find(@post.town_id)
    @towns = Town.all
    @categories = Category.all
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      if Town.find_by(name: @post.town_name)
        town_exist = Town.find_by(name: @post.town_name)
        @post.update(town_id: town_exist.id)
      else
        @post.update(town_id: nil)
      end
      redirect_to user_path(current_user.id)
    else
      @town = Town.find(@post.town_id)
      @towns = Town.all
      @categories = Category.all
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy!
    redirect_to user_path(current_user.id)
  end

  private
  def post_params
    params.require(:post).permit(:image,:town_id,:category_id,:title,:body,:town_name)
  end

end

akita-interest-mapping/app/controllers/publics/registrations_controller.rb
# frozen_string_literal: true

class Publics::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]

  protected

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email,:password,:last_name,:first_name,:last_name_kana,:first_name_kana,:nickname])
  end

end

akita-interest-mapping/app/controllers/publics/sessions_controller.rb
# frozen_string_literal: true

class Publics::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :user_state, only: [:create]

  def after_sign_out_path_for(resource)
    root_path
  end

  protected
  def user_state
    @user = User.find_by(email: params[:user][:email])
    return if !@user
    if @user.valid_password?(params[:user][:password]) && !@user.is_active
      redirect_to new_user_session_path
    end

  end

end

akita-interest-mapping/app/controllers/publics/unlocks_controller.rb
# frozen_string_literal: true

class Publics::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

akita-interest-mapping/app/controllers/publics/users_controller.rb
class Publics::UsersController < ApplicationController
  def index
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def edit
    @user = current_user
  end

  def update
  end

  def withdraw
    @user = current_user
    @user.update(is_active: false)
    reset_session
    redirect_to root_path
  end

end

akita-interest-mapping/app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

akita-interest-mapping/app/helpers/publics/homes_helper.rb
module Publics::HomesHelper
end

akita-interest-mapping/app/helpers/publics/posts_helper.rb
module Publics::PostsHelper
end

akita-interest-mapping/app/helpers/publics/users_helper.rb
module Publics::UsersHelper
end

akita-interest-mapping/app/views/publics/users/show.html.erb
<section class=" text-center">
    <div class="container">
      <h4 class="jumbotron-heading">
        <div class="row d-flex justify-content-center">
          <%= image_tag @user.get_profile_image(150,150),class: "rounded-circle" %><br>
        </div>
        ー　<%= @user.nickname %>　さんのページ　ー
      </h4>
      <p class="lead text-muted"><%= @user.introduction %></p>
      <p>
        <%= link_to "プロフィール編集",edit_user_path(current_user.id),class: "btn btn-primary my-2" %>
        <a href="#" class="btn btn-success my-2">お気に入り</a>
        <a href="#" class="btn btn-secondary my-2">非公開にする</a>
        <%= link_to "退会する",user_withdraw_path(current_user.id),class: "btn btn-danger my-2","data-confirm" => "本当に退会しますか？" %>

      </p>
    </div>
  </section>

  <div class="album py-5">
    <div class="container">

      <div class="row">
        <% @user.posts.each do |post| %>
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <%= image_tag post.image,class: "img-fluid" %>
            <div class="card-header">
                <span class="card-title h4 font-weight-bold"><%= post.title %></span>  
                <p>
                <small class="text-muted">市町村：<%= post.town.name %></p>
                <p>カテゴリ：<%= post.category.name %></small></p>  
            </div>
            <div class="card-body">
              <p class="card-text"><%= post.body %></p>
              <div class="d-flex justify-content-between align-items-center">
                <% if current_page?(user_path) %>
                <div class="btn-group">
                    <%= link_to "編集",edit_post_path(post.id),class: "btn btn-success","data-turbolinks": "false" %>    
                    <%= link_to "削除",post_path(post.id),method: :delete,class: "btn btn-danger","data-confirm" => "本当に削除しますか？" %>  
                  </div>
                <% end %>
                <small class="text-muted"><%= link_to user_path(post.user.id) do %>
                  ＠<%= post.user.nickname %>
                <% end %></small>
              </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>