akita-interest-mapping/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "publics/registrations",
    sessions: 'publics/sessions'
  }
  devise_for :admins, controllers: {
    sessions: "admins/sessions"
  }

  scope module: :publics do
    root to: 'homes#top'
    resources :users, only: [:index, :show, :edit, :update]
    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy]
    get 'users/:id/withdraw' => 'users#withdraw', as: 'user_withdraw'
  end

  namespace :admins do
    root to: 'homes#top'
    resources :users, only: [:index, :show, :edit, :update]
    resources :posts, only: [:index, :show, :edit, :update, :destroy]
  end
  
end

akita-interest-mapping/app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

akita-interest-mapping/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

akita-interest-mapping/app/models/category.rb
class Category < ApplicationRecord
  has_many :posts,dependent: :destroy
end

akita-interest-mapping/app/models/post.rb
class Post < ApplicationRecord
  attr_accessor :town_name
  belongs_to :user,optional: true
  belongs_to :town,optional: true
  belongs_to :category,optional: true    

  has_one_attached :image

  validates :image,presence: true
  validates :town,presence: true
  validates :category,presence: true
  validates :title,presence: true
end

akita-interest-mapping/app/models/town.rb
class Town < ApplicationRecord
  has_many :posts,dependent: :destroy

end

akita-interest-mapping/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :posts,dependent: :destroy

  has_one_attached :profile_image
  
  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path = Rails.root.join("app/assets/images/default_person.jpeg")
      profile_image.attach(io: File.open(file_path),filename: "default-image.jpg",content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

akita-interest-mapping/app/controllers/admins/homes_controller.rb
class Admins::HomesController < ApplicationController
  def top
  end
end

akita-interest-mapping/app/controllers/admins/sessions_controller.rb
# frozen_string_literal: true

class Admins::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  def after_sign_in_path_for(resource)
    admins_root_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end

end

akita-interest-mapping/app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

akita-interest-mapping/app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
end

akita-interest-mapping/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

akita-interest-mapping/app/controllers/publics/homes_controller.rb
class Publics::HomesController < ApplicationController
  def top
    @posts = Post.all
    @towns = Town.all
    @categories = Category.all
  end
end

akita-interest-mapping/app/controllers/publics/posts_controller.rb
class Publics::PostsController < ApplicationController
  def new
    @user = current_user
    @towns = Town.all
    @categories = Category.all
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if Town.find_by(name: @post.town_name)
      town = Town.find_by(name: @post.town_name)
      @post.town_id = town.id
      
    else
      @post.town_id = nil
    end
    @post.user_id = current_user.id
    if @post.save
      redirect_to user_path(current_user.id)
    else
      @user = current_user
      @towns = Town.all
      @categories = Category.all
      render :new
    end
  end

  def index
    @posts = Post.all
    @towns = Town.all
    @categories = Category.all
  end

  def show
  end

  def edit
    @post = Post.find(params[:id])
    @town = Town.find(@post.town_id)
    @towns = Town.all
    @categories = Category.all
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      if Town.find_by(name: @post.town_name)
        town_exist = Town.find_by(name: @post.town_name)
        @post.update(town_id: town_exist.id)
      else
        @post.update(town_id: nil)
      end
      redirect_to user_path(current_user.id)
    else
      @town = Town.find(@post.town_id)
      @towns = Town.all
      @categories = Category.all
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy!
    redirect_to user_path(current_user.id)
  end

  private
  def post_params
    params.require(:post).permit(:image,:town_id,:category_id,:title,:body,:town_name)
  end

end

akita-interest-mapping/app/controllers/publics/users_controller.rb
class Publics::UsersController < ApplicationController
  def index
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def edit
    @user = current_user
  end

  def update
  end

  def withdraw
    @user = current_user
    @user.update(is_active: false)
    reset_session
    redirect_to root_path
  end

end

akita-interest-mapping/app/helpers/admins/homes_helper.rb
module Admins::HomesHelper
end

akita-interest-mapping/app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

akita-interest-mapping/app/helpers/application_helper.rb
module ApplicationHelper
end

akita-interest-mapping/app/helpers/publics/homes_helper.rb
module Publics::HomesHelper
end

akita-interest-mapping/app/helpers/publics/posts_helper.rb
module Publics::PostsHelper
end

akita-interest-mapping/app/helpers/publics/users_helper.rb
module Publics::UsersHelper
end

akita-interest-mapping/app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

akita-interest-mapping/app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

akita-interest-mapping/app/views/layouts/_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <%= link_to "トップに戻る", root_path,class: "text-muted" %>
    </p>
    <p>このサイトは開発途中です。</p>
  </div>
</footer>

akita-interest-mapping/app/views/layouts/_header.html.erb
<header>
  <div class="bg-dark collapse" id="navbarHeader" style="">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">ようこそAkita Interest Mappingへ！</h4>
          <p class="text-muted">　このサイトは秋田で起きている面白そうなもの、楽しそうなもの、気になるものを共有するサイトです！<br>　秋田の情報にあふれて秋田の魅力をより多くの人に共有する目的で運営を予定しています！</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">メニュー</h4>
          <ul class="list-unstyled">
          <% if user_signed_in? %>
            <li>
              <%= link_to destroy_user_session_path,method: :delete do %>
                <i class="fas fa-sign-out-alt mx-2" ></i>ログアウト
              <% end %>
            </li>
            <li>
              <%= link_to root_path do %>
                <i class="fas fa-home mx-2" ></i>ホーム
              <% end %>
            </li>
            <li>
              <%= link_to user_path(current_user.id) do %>
                <i class="fas fa-user mx-2" ></i>マイページ
              <% end %>
            </li>
            <li>
              <%= link_to new_post_path do %>
                <i class="fas fa-edit mx-2" ></i>新規投稿
              <% end %>
            </li>

        <% elsif admin_signed_in? %>
          <li>
            <%= link_to destroy_admin_session_path, method: :delete do %>
              <i class="fas fa-sign-out-alt mx-2" ></i>ログアウト
            <% end %>
          </li>
          <li>
            <%= link_to admins_root_path do %>
              <i class="fas fa-home mx-2" ></i>ホーム
            <% end %>
          </li>
          <li>
            <%= link_to admins_users_path do %>
              <i class="fas fa-users mx-2" ></i>ユーザー一覧
            <% end %>
          </li>

        <% else %>
          <li>
            <%= link_to user_session_path do %>
              <i class="fas fa-sign-in-alt mx-2"></i>ログイン
            <% end %>
          </li>
          <li>
            <%= link_to root_path do %>
            <i class="fas fa-home mx-2"></i>ホーム
            <% end %>
          </li>
          <li>
            <%= link_to user_session_path do %>
              <i class="fas fa-user mx-2"></i>マイページ
            <% end %>
          </li>

        <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container d-flex justify-content-between">
        <strong><%= link_to root_path do %>
          Akita Interest Mapping
        <% end %></strong>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="true" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

akita-interest-mapping/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AkitaInterestMapping</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/2dff7017b4.js" crossorigin="anonymous"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-color:#CDE6C7;">
    <%= render 'layouts/header' %>
      <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>